In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [7]:
## loading the file
df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [8]:
# preprocess the data
# drop the unnecessary columns
df=df.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

In [9]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [10]:
#encoding the categorical data
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])

In [11]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [12]:
from  sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
encode_geo=ohe.fit_transform(df[["Geography"]]).toarray()
encode_geo

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [13]:
encode_geo=pd.DataFrame(encode_geo, columns=ohe.get_feature_names_out(["Geography"]))

In [14]:
encode_geo

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [15]:
#add these features
df=pd.concat([df.drop(['Geography'], axis=1), encode_geo], axis=1) 
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [16]:
## tosave endoder and scaler
with open("label_encoder.pkl", "wb") as file:
    pickle.dump(le, file)

with open("onehot_encoder.pkl", "wb") as file:
    pickle.dump(ohe, file)

In [17]:
# spliting in dependent and independent features
X=df.drop("Exited", axis=1)
y=df["Exited"]

# spliting in train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# feature scaling
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [18]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [19]:
with open("scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

In [20]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [21]:
import tensorflow as tf
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense
# from tensorflow.keras.callbacks import EarlyStopping,tensorboard
import datetime

WARNING:tensorflow:From d:\DATA SCIENCE\deep learning\ANN CLASIFICATION\conda_env\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

In [23]:
# bulid our ANN model
model = Sequential(
    [
        Dense(64, activation="relu", input_shape=(X_train.shape[1],)),  ##Hidden layer 1
        Dense(32, activation="relu"), ##Hidden layer 2
        Dense(1, activation="sigmoid") #Output    
    ]
)

WARNING:tensorflow:From d:\DATA SCIENCE\deep learning\ANN CLASIFICATION\conda_env\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [25]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.001)
loss=tensorflow.keras.losses.BinaryCrossentropy()

In [26]:
## compile the model
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

In [27]:
# set up the tensorboard
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [28]:
##setup the early stopping
early_stopping = EarlyStopping(monitor='val_loss',patience=5, restore_best_weights=True)

In [29]:
# train the model
history=model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, callbacks=[early_stopping, tensorboard_callback])

Epoch 1/100
WARNING:tensorflow:From d:\DATA SCIENCE\deep learning\ANN CLASIFICATION\conda_env\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\DATA SCIENCE\deep learning\ANN CLASIFICATION\conda_env\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 4ms/step - loss: 0.4680 - accuracy: 0.7871 - val_loss: 0.3913 - val_accuracy: 0.8305
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3772 - accuracy: 0.8454 - val_loss: 0.3528 - val_accuracy: 0.8545
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3508 - accuracy: 0.8550 - val_loss: 0.3452 - val_accuracy: 0.8600
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3446 - accuracy: 0.8560 - val_loss: 0.3448 - val_accuracy: 0.8625
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3401 - accuracy: 0.8581 - val_loss: 0.3473 - val_accuracy: 0.8605
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3359 - accuracy: 0.8585 - val_loss: 0.3437 - val_accuracy: 0.8610
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3337 - accuracy: 0.8631 - val_loss: 0.3437 - val_accuracy: 0.8600
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3325 - accuracy: 0.8619 - val_loss: 0.3422 - val_accuracy: 0.8590
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3295 - accuracy: 0.8633 - val_loss: 0.3445 - val_accuracy: 0.8620
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3272 - accuracy: 0.8645 - val_loss: 0.3410 - val_accuracy: 0.8625
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3254 - accuracy: 0.8660 - val_loss: 0.3414 - val_accuracy: 0.8615
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3240 - accuracy: 0.8649 - val_loss: 0.3387 - val_accuracy: 0.8585
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3224 - accuracy: 0.8649 - val_loss: 0.3399 - val_accuracy: 0.8605
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3198 - accuracy: 0.8681 - val_loss: 0.3382 - val_accuracy: 0.8635
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3192 - accuracy: 0.8656 - val_loss: 0.3433 - val_accuracy: 0.8575
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3166 - accuracy: 0.8694 - val_loss: 0.3446 - val_accuracy: 0.8590
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3158 - accuracy: 0.8687 - val_loss: 0.3380 - val_accuracy: 0.8600
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3145 - accuracy: 0.8679 - val_loss: 0.3454 - val_accuracy: 0.8620
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3139 - accuracy: 0.8695 - val_loss: 0.3377 - val_accuracy: 0.8630
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3114 - accuracy: 0.8704 - val_loss: 0.3394 - val_accuracy: 0.8635
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3099 - accuracy: 0.8705 - val_loss: 0.3383 - val_accuracy: 0.8630
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3094 - accuracy: 0.8683 - val_loss: 0.3410 - val_accuracy: 0.8640
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3076 - accuracy: 0.8715 - val_loss: 0.3404 - val_accuracy: 0.8630
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3059 - accuracy: 0.8742 - val_loss: 0.3425 - val_accuracy: 0.8615

In [30]:
model.save("churn_model.h5")

d:\DATA SCIENCE\deep learning\ANN CLASIFICATION\conda_env\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [31]:
## loading tensorboard
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [ ]:

%tensorboard --logdir logs/fit

In [37]:
import os
# Tells Jupyter's extension exactly where the binary is located
os.environ['TENSORBOARD_BINARY'] = r"conda_env\Scripts\tensorboard.exe"

# Load the extension and run TensorBoard
%load_ext tensorboard
%tensorboard --logdir="logs/fit"

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 6548), started 13:05:19 ago. (Use '!kill 6548' to kill it.)