In [23]:
import tensorflow as tf 
import numpy as np
import pandas as pd
from tensorflow.keras.models import load_model
import pickle

In [24]:
model = load_model("churn_model.h5")

with open("scaler.pkl", "rb") as file:
    scaler = pickle.load(file)

with open("label_encoder.pkl", "rb") as file:
    label_encoder = pickle.load(file)

with open("onehot_encoder.pkl", "rb") as file:
    onehot_encoder = pickle.load(file)

In [25]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [26]:
input_df= pd.DataFrame([input_data])

In [27]:
onehot_encoded_data = onehot_encoder.transform([[input_data['Geography']]]).toarray()
onehot_encoded_df = pd.DataFrame(onehot_encoded_data, columns=onehot_encoder.get_feature_names_out(['Geography']))
onehot_encoded_df

d:\DATA SCIENCE\deep learning\ANN CLASIFICATION\conda_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [28]:
input_df=pd.concat([input_df, onehot_encoded_df], axis=1)
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,France,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [29]:
## encode the categorical features]
input_df['Gender'] = label_encoder.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,France,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [30]:
input_df.drop('Geography', axis=1, inplace=True)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [31]:
## scaling the data
scaled_input = scaler.transform(input_df)
scaled_input

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [32]:
##predicting the output
prediction = model.predict(scaled_input)
prediction

1/1 [==============================] - 0s 445ms/step

array([[0.02647775]], dtype=float32)

In [33]:
prediction_probability = prediction[0][0]

In [34]:
if prediction_probability > 0.5:
    print(f"The customer is likely to churn with a probability of {prediction_probability:.2f}")
else:
    print(f"The customer is not likely to churn with a probability of {1 - prediction_probability:.2f}")

The customer is not likely to churn with a probability of 0.97